### ISSUE TITLE
Too many copies of protocolParams ending up in output files

### ISSUE THREAD

**Issue by gkaguirre** [BrainardLab/OneLightToolbox#12]
Jack and I went through the files that are produced by running an experiment.

The routine `OLReceptorIsolateMakeModulationStartsStops.m` places a copy of the protocolParams into a field of `modulationData`. This results in a copy of the protocol params being saved with every description of every trial from the experiment.

Separately, the "base" computer that is running an Approach experiment saves a file that contains the protocol params. 

Instead of having these multiple copies, we propose that it is the responsibility of the base routine (e.g., RunPulseSquintApproach) to save the protocolParams.

If there are no objections, I will delete line 205 of `OLReceptorIsolateMakeModulationStartsStops.m`.

**Comment by DavidBrainard** [comment]
Not sure whether the other shoe ever dropped here, but the Joris rewrite has probably made this obsolete in any case.  So, closing the issue.
