### ISSUE TITLE
OLPrimaryToSettings handles out of bounds primaries

### ISSUE THREAD

**Issue by JorisVincent** [BrainardLab/OneLightToolbox#13]
Primaries should be in the [0-1] range. OLPrimaryToSettings returns settings for primaries that are outside this range: a primary of 1s returns settings of 1, a primary of 2s also returns settings of 1, and a primary of -1s returns settings of 0. 

I propose that instead, it should check and throw an error if primary values are out of range -- the user should be aware (and held accountable) that they are asking impossible things.

[NOTE: OLSettingsToStartsStops _does_ check that _settings_ are in the [0-1] range]

**Comment by DavidBrainard** [comment]
JV and I added key/value pair to enable this checking, and set it to true.
