### ISSUE TITLE
Inconsistent orientation of returned SPD

### ISSUE THREAD

**Issue by JorisVincent** [BrainardLab/OneLightToolbox#14]
Sometimes we measure a spectrum, through `OLTakeMeasurementOOC`, and sometimes we simulate what we think the spectrum would be, through `OLPrimaryToSPD`. The former returns a rowvector, the latter returns a column vector.
To propagate the returned spectrum, subsequent code would have to know whether we simulated or measured, to deal with this inconsistency.

Do we want the responsibility for dealing with this on the user, or should these two functions return the same orientation (and if so, what orientation should that be)?

**Comment by spitschan** [comment]
Spectral power distributions should always be returned as column vectors, since this is the de facto standard in the larger PTB/Brainard/Wandell universe.

**Comment by DavidBrainard** [comment]
Agreed.  It is possible that something in the OL code will break if we make the switch, but we should probably do so and then fix whatever broke.

Sadly, the Wandell universe switched to row vectors for spectra at some point, which makes life hard when we interact with isetbio.  But we are not doing
too much of that here.  And PTB is very much a spectra in column vectors place.

**Comment by JorisVincent** [comment]
Closed by PR#19
