### ISSUE TITLE
Why is there a OLBoxBRandomized..._ND03.mat cal file in OneLightToolbox?

### ISSUE THREAD

**Issue by DavidBrainard** [BrainardLab/OneLightToolbox#20]
There is one in the OLDemoCal directory.  Why?  Can we delete it?

**Comment by JackRyan1989** [comment]
I have no idea as to why it is in there, possibly a relic from our coding spree with Michael Barnett last summer? I don't see any issue with deleting it.

**Comment by DavidBrainard** [comment]
Deleted file, closing issue.
