### ISSUE TITLE
Repo cannot always be cloned

### ISSUE THREAD

**Issue by JorisVincent** [BrainardLab/OneLightToolbox#25]
Tried cloning on Windows 10 (Pro, 64-bit, version 1709, build 16299.192), using GitKraken (version 3.3.4 64-bit), which failed.

It seems the file `OLLabJackLibrary/src/U3dev/U3original/.U3dev.` causes an invalid path error. This is likely because there is `.` at the end, without an extension. When cloning in another client (SourceTree 2.3.5.0) on the same system, this file was cloned as `OLLabJackLibrary/src/U3dev/U3original/.U3dev` without the stray period (and this showed up in my uncommitted changes).

Is there any reason not to rename to `.U3dev`?

**Comment by npcottaris** [comment]
This was handled by renaming `.U3dev.` to `.U3dev.makefile`
Closing this issue.
