### ISSUE TITLE
Move protocol names from localhook to Setup-script?

### ISSUE THREAD

**Issue by JorisVincent** [BrainardLab/OneLightToolbox#26]
Currently, the LocalHook an OLApproach defines the protocols used in that approach; in `OLApproach_PsychophysicsLocalHookTemplate`, one can find:
```
%% Define protocols for this approach
theProtocols = { ...
    'Demo' ...
    'MaxMelPulsePsychophysics' ...
    };
```
The main reason for this is because directories (e.g., `MELA_materials/...`) are protocol dependent, and need to be added to the preferences, which the LocalHooks do. 
However, while the `LocalHookTemplate` is under version control, specific LocalHooks are not. This means that adding in a new protocol requires generating a new LocalHook on each machine where an Approach is used. 

I propose that protocols are instead defined in the `Setup` script (e.g., `SetupPsychophysicsApproach`):
- This *is* under version control, meaning that protocols can be added/changed/removed without the need to manually update every LocalHook on every machine. 
- This script should then explicitly called by the LocalHook (and thus be added to the `LocalHookTemplate`), to add the protocols to the preferences. 
- The LocalHook will still define the base materials/data path for the entire approach, but the `Setup` script is in charge of arranging everything within those directories according to protocol. - This will result in the `Setup` script being called on every `tbUseProject('OLApproach_xxx')`, which I think would be preferred behavior anyway; 
  - the `Setup` script generates backgrounds and directions necessary for the OLApproach, and presumably you actually want those to exist when using the approach. 
  - This shouldn't add too much overhead onto the `tbUseProject`-call, because the backgrounds/directions should not be generated if they exist in cache. 
  - Thus, under this new proposal, `tbUseProject`-calls will check if background/directions exist for the approach, and generate them if they are missing/stale.

**Comment by gkaguirre** [comment]
Good idea.

**Comment by DavidBrainard** [comment]
I agree this is a good concept.  I do think, however, that we don't want the Setup script invoked by tbUseProject.  Among other things, we are often debugging the Setup script, and it can take a fair amount of time.

Instead, how about writing a short function in the approach, called something like DefineApproachProtocols, and have this return the protocols to the local hook?  This has the advantages of keeping as much machine independent code under version control as possible, as. you describe.  It could also be called safely by the approach setup script, if the same information is needed there.

If we ever decided that we really did want the local hook to call the setup script, we could at that point simply add the call in explicitly.

**Comment by JorisVincent** [comment]
This has now been implemented for OLApproach_Psychophysics (see https://github.com/BrainardLab/OLApproach_Psychophysics/commit/4bd7c8cdd91946ee0f1580b38f571bcd03cbfa50)
