### ISSUE TITLE
Reorganizing how data is stored

### ISSUE THREAD

**Issue by JorisVincent** [BrainardLab/OneLightToolbox#27]
Currently, in the `MELA_data` DropBox folder, files are stored according to the following hierarchy:
1. `protocol-name` (`DEMO`,`SquintToPulse`, etc.)
2. `file-type` (`DirectionCorrectedPrimaries`, `DirectionValidationFiles`, `DataFiles`, `SessionRecords`, `ModulationStartsStops`)
3. `subjectID`
4. `date`
5. `session` (`session_1` or [some other specified name](https://github.com/BrainardLab/OneLightToolbox/tree/0028824680439254986ae2d00c6fed81b2f168d5))

I propose we change this hierarchy, so that level 2 becomes level 5, i.e.:
1. `protocol-name` (`DEMO`,`SquintToPulse`, etc.)
3. **`subjectID`**
4. `date`
5. `session` 
2. **`file-type`**

This would have the feature that everything from a session is grouped together, rather than spread apart, which is more likely to create consistency between the different `file-type` directories. Plus, it would allow us to specify a single directory at the start of a session, which the rest is relative to, rather than separately specifying each directory for `directioncorrectedPrimaries`, `DataFiles`, etc.

Does anybody (@DavidBrainard, @gkaguirre, @JackRyan1989, @harrison-mcadams) know a reason _not_ to do this?

**Comment by JorisVincent** [comment]
If I recall correctly @DavidBrainard and I posted this on Slack at some point, but I don't remember if we ever discussed further.

**Comment by JorisVincent** [comment]
And, on further thought, do we need to also capture `date` in the directory structure? Is there a conceivable case in which we would want to label sessions with identical names/numbers, on different dates?

**Comment by DavidBrainard** [comment]
I think this general plan is fine.  But, I vote for keeping the date level in the tree -- it's often useful to be able to scan the tree and quickly find the stuff that goes with some subject/date.

**Comment by JorisVincent** [comment]
I've updated `OLApproach_PsychophysicsLocalHookTemplate` to set just a single pref for each protocol, defining the basepath for the datafiles: 
```DataFilesBasePath: '/Users/<user>/Dropbox (Aguirre-Brainard Lab)/MELA_data/Experiments/OLApproach_Psychophysics/<protocolName>'```

It is up to the individual protocols to create the `/<subjectID>/<date_sessionID>/<acquisition>` subdirectories.

And it is up to us to ensure consistency across protocols and approaches (or deviate from consistency where it makes sense).
