### ISSUE TITLE
Close branch master_020118

### ISSUE THREAD

**Issue by JorisVincent** [BrainardLab/OneLightToolbox#30]
We brached `master_020118` to preserve a stable branch for the squint approach while I was updating the OneLightToolbox. The OLApproach_Squint has since been updated to the current master, and successfully run under real conditions today.

If there are no objections (@DavidBrainard, @gkaguirre), I'll delete this branch. A [release-tag](https://github.com/BrainardLab/OneLightToolbox/commit/f485b19779401a1d6f379dc6ac23df8f2b472567) to the branch point remains, so we can always rollback if necessary.

**Comment by DavidBrainard** [comment]
Fine with me.

David

**Comment by JorisVincent** [comment]
Deleted the branch.
