### ISSUE TITLE
Temperature measurements during calibration not working

### ISSUE THREAD

**Issue by JorisVincent** [BrainardLab/OneLightToolbox#33]
`OLCalibrateOOC` cannot seem to open the LabJack UE3 hooked up to BoxD in the psychophysics room. It gives the following error during `LJTemperatureProbe.open()`[54]:`                LJTemperatureProbeU3('open');`

`Failed with message: 'Requested 4294967297x8243118308125329996 (17179869184.0GB) array exceeds maximum array size preference. Creation of arrays greater than this limit may take a long time and cause MATLAB to become unresponsive. See array size limit or preference panel for more information.'.`

This is on MacBook Pro GKA34, OS Sierra (10.12.6). I _believe_ I have previously used this laptop/LabJack combo succesfully.

**Comment by npcottaris** [comment]
This is now fixed. A couple of variables in the `U3.c` file were declared as` int`, whereas they should have been declared as `size_t`. This was a warning and was running without crashing before Sierra, but it became problematic in Sierra. Fix pushed to master.
